[package]
name = "merkle-tree"
version = "0.1.0"
authors = ["andelf <andelf@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.7"

[dev-dependencies]
sha2 = "0.9"
