[package]
name = "keys"
version = "0.1.0"
authors = ["OpenTron Developers <info@opentron.org>"]
edition = "2021"

[dependencies]
base58 = "0.2"
hex = "0.4"
sha2 = "0.10"
sha3 = "0.10"
digest = "0.10"
libsecp256k1 = "0.7"
rand = "0.8"
